#!/usr/bin/env python3
"""Build self-contained Claude agents from the same guidance Codex reads."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('plugins/personal-prs-agent/skills/personal-prs-agent/references/specialists')
DESTINATION = Path('plugins/personal-prs-agent/agents')
ROLES = {
    'reviewer-logic': 'Review changed behavior, edge cases, concurrency, and security boundaries for the Personal PRs Agent leader.',
    'reviewer-architecture': 'Review changed API contracts, ownership, and integration boundaries for the Personal PRs Agent leader.',
    'reviewer-tests-quality': 'Review regression coverage and test validity using current repository tooling for the Personal PRs Agent leader.',
    'reviewer-accessibility': 'Review UI changes for keyboard, focus, semantics, and accessible interaction for the Personal PRs Agent leader.',
    'reviewer-acceptance': 'Compare changes with supplied acceptance criteria for the Personal PRs Agent leader.',
}

def render(root, name, description):
    shared = (root / SOURCE / 'contract.md').read_text().strip()
    specific = (root / SOURCE / (name + '.md')).read_text().strip()
    return (f'---\nname: {name}\ndescription: {description}\ntools: Read, Grep, Glob\n'
            'model: inherit\n---\n\n'
            '<!-- Generated by scripts/build_claude_agents.py; edit the shared specialist sources. -->\n\n'
            + shared + '\n\n' + specific + '\n')

def check(root):
    stale = []
    for name, description in ROLES.items():
        file = root / DESTINATION / (name + '.md')
        if not file.is_file() or file.read_text() != render(root, name, description):
            stale.append(file.name)
    if (root / DESTINATION).exists():
        stale.extend(p.name for p in (root / DESTINATION).glob('*.md') if p.stem not in ROLES)
    return sorted(stale)

def build(root):
    (root / DESTINATION).mkdir(parents=True, exist_ok=True)
    for name, description in ROLES.items():
        (root / DESTINATION / (name + '.md')).write_text(render(root, name, description))

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if not args.check:
        build(ROOT)
    stale = check(ROOT)
    if stale:
        print('Agent definitions missing or out of sync: ' + ', '.join(stale))
        return 1
    print('Claude agent definitions match the shared specialist sources.')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
